sonar.projectKey=SMART
sonar.projectName=SmartLogix
sonar.projectVersion=1.0

# Define la ruta al código que deseas escanear. 
# Si tu código está en la raíz, déjalo como un punto (.). 
# Si está en una subcarpeta (ej. src), cambia el punto por src.
sonar.sources=.

# Ignora carpetas de dependencias o compilación para no saturar el análisis
sonar.exclusions=**/node_modules/**, **/bin/**, **/obj/**, **/dist/**

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
